export const allPrompts = [
    "Explain quantum computing in simple terms",
    "Give me ideas for a healthy dinner",
    "Write a short story about a robot discovering emotions",
    "Summarize the latest news in AI",
    "What are the benefits of cloud computing?",
    "How does photosynthesis work?",
    "Describe how machine learning works",
    "What is blockchain and how does it work?",
    "Write a haiku about spring",
    "Give me a workout plan for beginners",
    "Explain relativity in simple terms",
    "Write a joke about cats and programmers",
    "How do black holes form?",
    "What is the meaning of life?",
    "Create a packing list for a trip to Iceland",
    "How do you make sourdough bread?",
    "Write a poem about time travel",
    "What are the pros and cons of remote work?",
    "How does the immune system work?",
    "Describe the water cycle",
    "Generate a fun fact about space",
    "List five ways to reduce stress",
    "Write a bedtime story for a child",
    "What is quantum entanglement?",
    "Give me a productivity tip",
    "Explain recursion with an example",
    "How do plants grow?",
    "What’s the history of the internet?",
    "Create a recipe with chickpeas",
    "Describe a perfect morning routine",
    "Explain how GPS works",
    "Summarize the theory of evolution",
    "Give me tips for better sleep",
    "What’s an elevator pitch for AI?",
    "Generate a random inspirational quote",
    "Explain what an API is",
    "Write a tweet about mental health",
    "How does a car engine work?",
    "Describe a utopian society",
    "What's the difference between AI and ML?",
    "Write a joke about ducks",
    "Create a 3-day meal plan",
    "What are cognitive biases?",
    "Explain why the sky is blue",
    "List three fun science experiments",
    "How do birds navigate?",
    "What is a neural network?",
    "Give me a startup idea",
    "What are the steps of the scientific method?",
    "Write a dialogue between two time travelers",
    "What is the Fibonacci sequence?",
    "Describe a black swan event",
    "How does a vaccine work?",
    "What's the difference between HTML and CSS?",
    "Suggest 5 books about creativity",
    "What’s a habit-forming strategy?",
    "How do you write a novel?",
    "Describe Mars as if you're a travel agent",
    "Give me ideas for a tech podcast",
    "What’s the Turing Test?",
    "Explain climate change to a 10-year-old",
    "How does an airplane fly?",
    "What are the types of clouds?",
    "Write a short love letter",
    "Give me a marketing slogan for tea",
    "Create a superhero based on sunlight",
    "Write a code comment that's too honest",
    "Describe a haunted house in 2 sentences",
    "What is the placebo effect?",
    "Write a pirate-themed knock-knock joke",
    "List 3 strategies for deep work",
    "What are logical fallacies?",
    "Summarize the book '1984'",
    "Generate a fantasy creature name",
    "How does a compass work?",
    "Explain the Big Bang theory",
    "What is dark matter?",
    "What’s the science behind rainbows?",
    "Create a riddle about time",
    "What is string theory?",
    "Write a birthday message for a coder",
    "Give me 5 creative writing prompts",
    "What’s a paradox in logic?",
    "Explain Newton’s laws",
    "How does a microwave work?",
    "Write an email to your future self",
    "What are some moon facts?",
    "Explain a meme in scholarly terms",
    "Write a horror story in 3 sentences",
    "What are some underrated skills?",
    "Summarize a day in the life of an astronaut",
    "How do bees make honey?",
    "What's the golden ratio?",
    "What is augmented reality?",
    "How does encryption work?",
    "Create a 1-minute meditation script",
    "Write a travel tip for Japan",
    "Describe the inside of a volcano",
    "What is Moore's Law?",
    "List 5 weird inventions",
    "Explain cryptocurrency simply",
    "Give me ideas for a science fair project"
];
